spring:
  kafka:
    consumer:
      group-id: test-group
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9092

flaxinger-kafka:
  topic-name: test-topic
  messages-per-request: 10
